# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arena2aisvr.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import custom_pb2 as custom__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61rena2aisvr.proto\x12\x10\x61rena.gorge_walk\x1a\x0c\x63ustom.proto\"\xe5\x01\n\x0f\x41IServerRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_no\x18\x02 \x01(\x05\x12*\n\x03obs\x18\x03 \x01(\x0b\x32\x1d.arena.gorge_walk.Observation\x12/\n\nscore_info\x18\x04 \x01(\x0b\x32\x1b.arena.gorge_walk.ScoreInfo\x12\x12\n\nterminated\x18\x05 \x01(\x05\x12\x11\n\ttruncated\x18\x06 \x01(\x05\x12+\n\x08\x65nv_info\x18\x07 \x01(\x0b\x32\x19.arena.gorge_walk.EnvInfo\"r\n\x10\x41IServerResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_no\x18\x02 \x01(\x05\x12(\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x18.arena.gorge_walk.Action\x12\x11\n\tstop_game\x18\x04 \x01(\x05\x42SZQgit.woa.com/king-kaiwu/framework/kaiwu_env/protocol/golang/arena_proto/gorge_walkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arena2aisvr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZQgit.woa.com/king-kaiwu/framework/kaiwu_env/protocol/golang/arena_proto/gorge_walk'
  _globals['_AISERVERREQUEST']._serialized_start=54
  _globals['_AISERVERREQUEST']._serialized_end=283
  _globals['_AISERVERRESPONSE']._serialized_start=285
  _globals['_AISERVERRESPONSE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
